[theme]
primaryColor = "#035F8A"      # Orange-red color
backgroundColor = "#FFFFFF"   # Light gray background
secondaryBackgroundColor = "#F0F0F0"  # White for secondary areas
textColor = "#000000"         # Black text
font = "Georgia, serif"          # Font type (e.g., 'serif', 'monospace')
